[allowlist]
  description = "Global Allowlist"

  paths = [
    # Ignore control-plane.yaml
    '''\.*/control-plane.yaml''',
    '''\.*/defaults/main.yml''',
    # Ignore poap.cfg
    '''scenarios/.*/poap.cfg''',
  ]
