---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  labels:
    osp/nncm-config-type: standard
  name: master-0-ctlplane
  namespace: openstack
spec:
  desiredState:
    interfaces:
    - name: internalapi
      type: vlan
      description: internalapi vlan interface
      ipv4:
        enabled: false
      ipv6:
        address:
        - ip: 2620:cf:cf:bbbb::10
          prefix-length: 64
        dhcp: false
        enabled: true
      mtu: 1442
      state: up
      vlan:
        base-iface: eth1
        id: "20"
    - name: storage
      type: vlan
      description: storage vlan interface
      ipv4:
        enabled: false
      ipv6:
        address:
        - ip: 2620:cf:cf:cccc::10
          prefix-length: 64
        dhcp: false
        enabled: true
      mtu: 1442
      state: up
      vlan:
        base-iface: eth1
        id: "21"
    - name: tenant
      type: vlan
      description: tenant vlan interface
      ipv4:
        enabled: false
      ipv6:
        address:
        - ip: 2620:cf:cf:eeee::10
          prefix-length: 64
        dhcp: false
        enabled: true
      mtu: 1442
      state: up
      vlan:
        base-iface: eth1
        id: "22"
    - description: ctlplane interface
      mtu: 1442
      name: eth1
      state: up
      type: ethernet
    - name: ospbr
      type: linux-bridge
      description: linux-bridge over ctlplane interface
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: eth1
          vlan: {}
      ipv4:
        enabled: false
      ipv6:
        address:
        - ip: 2620:cf:cf:aaaa::10
          prefix-length: 64
        dhcp: false
        enabled: true
      mtu: 1442
      state: up
  nodeSelector:
    kubernetes.io/hostname: master-0
    node-role.kubernetes.io/worker: ""
