---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ironic
  namespace: sushy-emulator
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "ironic",
      "type": "bridge",
      "bridge": "ironic",
      "mtu": 1442,
      "ipam": {
        "type": "whereabouts",
        "range": "2620:cf:cf:ffff::/64",
        "range_start": "2620:cf:cf:ffff::71",
        "range_end": "2620:cf:cf:ffff::75"
      }
    }
