---
stages:
  - name: Dependencies
    documentation: |
      Install and configure base dependencies required for OpenStack deployment,
      including operators, CRDs, and prerequisite services.
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/deps-stages.yaml.j2")
      }}

  - name: Cinder LVM
    documentation: |
      Configure LVM storage backend for Cinder block storage service.
      Sets up volume groups and prepares storage for OpenStack volumes.
    stages: >-
      {{
        lookup("ansible.builtin.file",
               "common/stages/cinder-lvm-label-stages.yaml")
      }}

  - name: TopoLVM
    documentation: |
      Deploy TopoLVM for local storage management on OpenShift nodes.
      Provides dynamic provisioning of local storage volumes.
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/topolvm-stages.yaml.j2")
      }}

  - name: OLM Openstack
    documentation: |
      Install OpenStack operators via Operator Lifecycle Manager (OLM).
      Deploys the OpenStack operator catalog and subscriptions.
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/olm-openstack-stages.yaml.j2")
      }}

  - name: NodeNetworkConfigurationPolicy (nncp)
    documentation: |
      Configure network interfaces and VLAN trunk setup on OpenShift nodes.
      Creates VLAN interfaces for OpenStack service networks (internalapi, storage,
      tenant, ironic) on a single trunk interface.
    manifest: manifests/networking/nncp.yaml
    wait_conditions:
      - >-
        oc wait -n openstack nncp -l osp/nncm-config-type=standard
        --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
        --timeout=180s

  - name: NetworkAttchmentDefinition (NAD)
    documentation: |
      Create NetworkAttachmentDefinitions for OpenStack service networks.
      Defines how pods can attach to the different VLAN-based networks.
    manifest: manifests/networking/nad.yaml

  - name: MetalLB - L2Advertisement and IPAddressPool
    documentation: |
      Configure MetalLB load balancer with IP address pools and L2 advertisements.
      Creates IP pools for all OpenStack service networks including the ironic network.
    manifest: manifests/networking/metallb.yaml

  - name: Netconfig
    documentation: |
      Configure OpenStack networking with NetConfig custom resource.
      Defines network configuration for OpenStack services.
    manifest: manifests/networking/netconfig.yaml

  - name: OpenstackControlPlane
    documentation: |
      Deploy the OpenStack control plane with all services configured.
      Includes Keystone, Nova, Neutron, Glance, Cinder, Swift, Ironic, and supporting services.
    manifest: manifests/control-plane/control-plane.yaml
    wait_conditions:
      - >-
        oc -n openstack wait openstackcontrolplanes.core.openstack.org controlplane
        --for condition=OpenStackControlPlaneDNSReadyCondition --timeout=600s

  - name: Extra DNS LoadBalancer on Ironic network
    documentation: |
      Deploy additional DNS service on the Ironic network for bare metal provisioning.
      Provides DNS resolution for ironic nodes during deployment and inspection.
    manifest: manifests/control-plane/dnsmasq-dns-ironic.yaml
    wait_conditions:
      - >-
        oc wait -n openstack service dnsmasq-dns-ironic
        --for jsonpath='.status.loadBalancer' --timeout=60s

  - name: Wait for OpenstackControlPlane
    documentation: |
      Wait for the OpenStack control plane to be fully ready and operational.
      Ensures all services are running before proceeding with additional configurations.
    wait_conditions:
      - >-
        oc wait -n openstack openstackcontrolplane controlplane
        --for condition=Ready --timeout=30m

  - name: Update openstack-operators OLM
    documentation: |
      Update OpenStack operators to newer versions via OLM subscriptions.
      Only runs when openstack_operators_update is defined and set to true.
    stages: >-
      {{
        lookup('ansible.builtin.template',
               'common/stages/openstack-olm-update.yaml.j2')
      }}
    run_conditions:
      - >-
        {{
          openstack_operators_update is defined and
          openstack_operators_update | bool
        }}

  - name: Wait for condition MinorUpdateAvailable True
    documentation: |
      Wait for OpenStack version to indicate that a minor update is available.
      This condition must be met before proceeding with version updates.
    wait_conditions:
      - >-
        oc -n openstack wait openstackversions.core.openstack.org controlplane
        --for=condition=MinorUpdateAvailable=True --timeout=10m
    run_conditions:
      - "{{ openstack_update is defined and openstack_update | bool }}"

  - name: "Minor update :: Create OpenStackVersion patch"
    documentation: |
      This creates a patch file `{{ manifests_dir }}/patches/openstack_version_patch.yaml`
      If `openstack_update_custom_images` is defined it will populate the customContainerImages
      in the OpenstackVersion YAML patch.
    shell: >-
      {{
        lookup('ansible.builtin.template',
              'common/scripts/create_openstack_version_patch.sh.j2')
      }}
    run_conditions:
      - "{{ openstack_update is defined and openstack_update | bool }}"

  - name: "Minor update :: Update the target version in the OpenStackVersion custom resource (CR)"
    documentation: |
      The `hotstack-openstack-version-patch` script will get the `availableVersion`
      and us it to replace the string `__TARGET_VERSION__` in the patch file and
      apply the patch using `oc patch` command.
    command: >-
      hotstack-openstack-version-patch --namespace openstack --name controlplane
      --file {{ manifests_dir }}/patches/openstack_version_patch.yaml
    wait_conditions:
      - oc -n openstack wait openstackversions.core.openstack.org controlplane
        --for=condition=Ready --timeout=10m
    run_conditions:
      - "{{ openstack_update is defined and openstack_update | bool }}"
